config/routes.rb
Rails.application.routes.draw do

  root 'cuisines#index'

  get "signup" => "users#new"
  post "signup" => "users#create"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  post "logout" => "sessions#destroy"

  get "cuisines/tag/:tag" => "cuisines#tag", as: :tag

  get "cuisines/results" => "cuisines#result", as: :results

  resources :cuisines
  get '*path', to: 'application#not_found'

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  validates :name,  presence: true, uniqueness: { message: "Cuisine already added. Please try again." }, numericality:false
  validates :recipe,  presence: true, length: { minimum: 10, maximum: 155, message: "Please include at least 2 related recipies and at most 200" }, uniqueness: true

  has_and_belongs_to_many :tags

end

app/models/cuisines_tags.rb
class CuisinesTags < ActiveRecord::Base
  belongs_to :cuisine
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :cuisines

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false }

  validates_confirmation_of :password, on: :create
  validates_presence_of :password_confirmation

  def self.authenticate email,password
    User.find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # refer to this to check for error in our main controller
  def not_found
    raise ActionController::RoutingError.new('Page Not Found')
  end

  def is_authenticated?
    redirect_to login_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  before_action :is_authenticated?

  def index
    @cuisines = Cuisine.all
    # render json:@photo
    # flash[:notice] = "Welcome to the page"
  end

  def result
    @search = params[:text]
    @list = flickr.photos.search :text => @search+' '+'street food', :sort => 'relevance'
    @results = @list.map do |photo|
      [FlickRaw.url_q(photo),
      FlickRaw.url_c(photo)]
    end
  end

  def new
    @cuisine = Cuisine.new
    @tags = Tag.all
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    @tags = Tag.all
    list = flickr.photos.search :text => @cuisine.name+' '+'street food', :sort => 'relevance'
    @cuisine.url = FlickRaw.url_q(list[0])

    if @cuisine.save
      @cuisine.tags.clear
      tags = params[:cuisine][:tag_ids].split(',')
      # render json:tags

      tags.each do |tag|
        @cuisine.tags << Tag.find_or_create_by(name: tag) unless tag.blank?
      end

      flash[:success] = "Your cuisine has been added"
      redirect_to cuisines_path
    else
      # flash is a variable and you are adding a value "string" to it
      flash[:notice] = "Unable to create new Cuisine"
      render :new
    end
  end

  def update
    @cuisine = Cuisine.find(params[:id]) or not_found

    if @cuisine.update(cuisine_params)
      redirect_to @cuisine
    else
      render 'edit'
    end

    tags = params[:cuisine][:tag_ids].split(',')

    @cuisine.tags.clear

    tags.each do |tag|
      @cuisine.tags << Tag.find_or_create_by(name: tag) unless tag.blank?
    end

  end

  def edit
    @cuisine = Cuisine.find(params[:id]) or not_found
    @tags = @cuisine.tags
  end

  def show
    @cuisine = Cuisine.find_by_id(params[:id]) or not_found
    @tags = @cuisine.tags.map do |tag|
              tag.name+" "
            end
    not_found unless @cuisine

    @search = @cuisine.name
    @list = flickr.photos.search :text => @search+' '+'street food', :sort => 'relevance'
    # render json:list

    @results = @list.map do |photo|
      [FlickRaw.url_q(photo),
      FlickRaw.url_c(photo)]
    end

  end

  def destroy
    @cuisine = Cuisine.find_by_id(params[:id]) or not_found
    @cuisine.destroy

    redirect_to cuisines_path
  end

  # searching for a specific tag
  def tag
      tag = Tag.find_by_name(params[:tag]) or not_found
      @cuisines = tag ? tag.cuisines : []
  end

  private

  def tag_params
    # params.require(:cuisine).permit(:tag_ids)
  end

  def cuisine_params
    params.require(:cuisine).permit(:name, :recipe)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :current_user

  def new

  end

  def create
    @user = User.authenticate(params[:user][:email],params[:user][:password])

    # render json:@user
    if @user
      session[:user_id] = @user.id
      flash[:success] = 'You have been logged in!'
      redirect_to root_path
    else
      flash[:success] = 'Credentials invalid! Please try again'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've been logged out!"
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Successful sign-in"
      redirect_to login_path
    else
      flash[:notice] = "Unable to sign-up, please try again"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/edit.html.erb
<div class='content'>
  <h2>Edit Cuisine</h2>
  <%= bootstrap_form_for :cuisine, url: cuisine_path(@cuisine), method: :patch do |f| %>
      <% if @cuisine.errors.any? %>
      <div id="error_explanation">
      <h3><%= pluralize(@cuisine.errors.count, 'Error') %>
         prohibited this cuisine from being saved:</h3>
        <ul>
          <% @cuisine.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <%= f.text_field :name, class: 'text-field',:placeholder => 'Update cuisine name'%>
      <%= f.text_area :recipe, class: 'text-area', :placeholder => 'Update the recipies for this cuisine?' %>
      <%= f.text_field :tag_ids, 'value' => @tags.map{|tag| tag.name}.join(","), class: 'tag-cloud', 'data-role'=>'tagsinput',  hide_label: :true %>
      <%= f.submit :class =>'btn btn-primary' %>
    <% end %>

    <%= link_to 'Back', cuisines_path, :class => 'btn btn-primary'%>
</div>

app/views/cuisines/index.html.erb
<div class='row top_content'>
  <div class='col-xs-6 col-md-6'>
    <h2>Get Your Nom On</h2>
    <p>Begin your street food search by clicking <span class='glyphicon glyphicon-camera'></span> on a cuisine below.</p>
    <p>Don't see what you like? Click "Add a Cuisine" to include your favorite.</p>
  </div>
  <div class='text-center col-xs-6 col-md-6'>
    <img src='http://i.imgur.com/G2xyPJj.jpg'>
  </div>
</div>

<%= render partial: "partials/flash" %>

<div class='row text-center grid_content'>
  <% @cuisines.each do |cuisine| %>
  <div class='col-xs-3 col-md-3 text-center cuisine_content'>
    <h2><%= cuisine.name %></h2>
    <%= image_tag(cuisine.url) %><br>
    <%= link_to '', cuisine, :class => 'glyphicon glyphicon-camera glyph-index' %> <%= link_to '', cuisine_path(cuisine), method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }, :class => 'glyphicon glyphicon-remove glyph-index' %><%= link_to '', edit_cuisine_path(cuisine), :class => 'glyphicon glyphicon-pencil glyph-index' %>
  </div>
  <% end %>
</div>

app/views/cuisines/new.html.erb
<div class='content'>
  <h2>Add new!</h2>

  <div class='row'>
    <div class='col-md-4 form-field'>
      <% if @cuisine.errors.any? %>
        <% @cuisine.errors.full_messages.each do |err_message| %>
          ! <%= err_message %><br>
        <% end %>
      <% end %>

      <%= bootstrap_form_for @cuisine do |f| %>
          <%= f.text_field :name, class: 'form-text', :placeholder => 'Cuisine type' %>
          <%= f.text_area :recipe, class: 'text-area form-text', :placeholder => 'What are your favorite recipes from this region?' %>
          <%= f.text_field :tag_ids, :value => "", class: 'tag-cloud form-text', 'data-role'=>'tagsinput', :placeholder => '#Hashtags', hide_label: :true  %>
          <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cuisines/result.html.erb
<div class='content'>
  <h2>Photos of "<%= @search %>"</h2>
  <br />
  <div class='text-center'>
    <% @results.each do |photo| %>
        <%= link_to image_tag(photo.first), photo.last %>
    <% end %>
  </div>
</div>

app/views/cuisines/show.html.erb
<div class='content'>
  <h2><%= @cuisine.name %> Street Food</h2>
  <p><span class='glyphicon glyphicon-tags'></span>
    <% @cuisine.tags.each do |tag|%>
      <%= link_to tag.name, tag_path(tag.name) %>
    <% end %></p>
  <br />
  <div class='text-center'>
    <% @results.each do |photo| %>
        <%= link_to image_tag(photo.first), photo.last %>
    <% end %>
  </div>
</div>

app/views/cuisines/tag.html.erb
<br>
<br>
<div class='container'>
  <div class='row table'>
    <div class='col-md-4'><h2>Cuisine</h2></div>
    <div class='col-md-5 '><h2><span class='glyphicon glyphicon-tags glyphicon-lg'></span></h2></div>
    <div class='col-md-2 text-center'><h2>Remove</h2></div>
  </div>
  <% @cuisines.each do |cuisine| %>
  <div class='row table'>
    <div class='col-md-4'>
      <%= cuisine.name %>
    </div>
    <div class='col-md-5'>
      <% cuisine.tags.each do |tag| %>
        <div class='tag-boarder'>
          <%= link_to tag.name, tag_path(tag.name) %>
        </div>
      <% end %>
    </div>
    <div class='col-md-2 text-center'><span class='glyphicon glyphicon-remove'></span></div>
  </div>
  <% end %>
</div>

app/views/cuisines/testing.html.erb
<table class='table'>
  <tr>
    <td><b>Cuisine</b></td>
    <td><b>Favorite Recipies</b></td>
    <td><b>View</b></td>
    <td><b>Remove</b></td>
    <td><b>Edit</b></td>
  </tr>
  <% @cuisines.each do |cuisine| %>
  <tr>
    <td><%= cuisine.name %></td>
    <td><%= cuisine.recipe %></td>
    <td class='text-center'><%= link_to '', cuisine, :class => 'glyphicon glyphicon-camera' %></td>
    <td class='text-center'><%= link_to '', cuisine_path(cuisine), method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }, :class => 'glyphicon glyphicon-remove' %></td>
    <td class='text-center'><%= link_to '', edit_cuisine_path(cuisine), :class => 'glyphicon glyphicon-pencil' %></td>

  <tr>
  <% end %>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streaterie</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Fredoka+One">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<script>
</script>

<% if @current_user %>

  <body>
  <div class='page-header'>
      <h1>
        <strong>Streaterie</strong>
      </h1>
  </div>
  <!-- ze navbar -->
  <nav class='container navbar navbar-default' role='navigation'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle' data-toggle='collapse'
        data-target='#example-navbar-collapse'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
    </div>
    <div class='container collapse navbar-collapse' id='example-navbar-collapse'>
      <ul class='nav navbar-nav'>
        <li class='nav-item'><%= link_to 'Home', root_path %></li>
        <li class='nav-item'><%= link_to 'Add a Cuisine', new_cuisine_path %></li>
        <li class='nav-item'><%= link_to 'Logout', logout_path %></li>
      </ul>

    <!-- Search Bar RH Side -->
     <form class="navbar-form navbar-right" role="search">
      <%= form_tag results_path, :class=> "navbar-form navbar-right", :method => "get" do %>
      <%= text_field_tag :text, nil, :class=> "form-control", :placeholder => "Browse street food" %>
      <%= submit_tag "Search", :class=>'btn btn-primary', :name => nil %>
      <% end %>

    </div>
  </nav>

  <div class='container'>
    <div class='container'>

    <%= yield %>

    </div>
  </div>

  </body>
  </html>

<% else %>

  <body>
  <div class='page-header'>
      <h1>
        <strong>Streaterie</strong>
      </h1>
  </div>
  <!-- ze navbar -->
  <nav class='container navbar navbar-default' role='navigation'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle' data-toggle='collapse'
        data-target='#example-navbar-collapse'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
    </div>
    <div class='container collapse navbar-collapse' id='example-navbar-collapse'>
      <ul class='nav navbar-nav'>
        <li class='nav-item'><%= link_to 'Sign-Up', signup_path %></li>
        <li class='nav-item'><%= link_to 'Login', login_path %></li>
      </ul>
    </div>
  </nav>
  <div class='container'>
    <div class='container'>

    <%= yield %>

    </div>
  </div>

  </body>
  </html>

<% end %>

app/views/partials/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |key,message| %>
    <div class='alert alert-<%= key %>'><%= message %></div>
    <br>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up </h2>

<div class='row'>
  <div class='col-xs-6 col-md-6'>
    <%= render partial: "partials/flash" %>
    <%= bootstrap_form_for :user do |f| %>
      <%= f.text_field :name, placeholder: "Enter your name" %>
      <%= f.email_field :email, placeholder: "Enter your email" %>
      <%= f.password_field :password, placeholder: "Enter your password"%>
      <%= f.password_field :password_confirmation, placeholder: "Re-enter your password"%>
      <%= f.submit "Sign-up"%>
  <% end %>
  </div>
</div>
<br>